# Generated by Django 5.0.1 on 2024-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
