# Generated by Django 5.0.1 on 2024-08-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_subject_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="admin",
        ),
    ]
