# Generated by Django 5.0.1 on 2024-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_student_email_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='courses',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
