# Generated by Django 5.0.1 on 2024-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_student_password_courses_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='password',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
